-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Nov 09, 2022 at 08:27 AM
-- Server version: 10.4.24-MariaDB
-- PHP Version: 7.4.29

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `happykids`
--

-- --------------------------------------------------------

--
-- Table structure for table `books`
--

CREATE TABLE `books` (
  `id` int(11) NOT NULL,
  `book_name` varchar(200) NOT NULL,
  `description` text NOT NULL,
  `author` varchar(200) NOT NULL,
  `publisher` varchar(200) NOT NULL,
  `price` varchar(200) NOT NULL,
  `quantity` int(11) NOT NULL,
  `categoryId` int(11) NOT NULL,
  `book_image` varchar(200) NOT NULL,
  `create_date` timestamp NOT NULL DEFAULT current_timestamp(),
  `userId` int(11) NOT NULL,
  `status` enum('1','0') NOT NULL DEFAULT '0' COMMENT '1 = published | 0 = unpublished'
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `books`
--

INSERT INTO `books` (`id`, `book_name`, `description`, `author`, `publisher`, `price`, `quantity`, `categoryId`, `book_image`, `create_date`, `userId`, `status`) VALUES
(1, 'A Life of Triumph', 'There is a power from within that can lift your heart from despair to hope, from hardship to happiness and from defeat to triumph. Ryuho Okawa introduces key attitudes to tap the endless reserves of positivity that are already a part of us. We may not be able to avoid setbacks, failures and mistakes in life, but we do not have to let them defeat us. We can all persevere when we become aware of the winner within!\r\n\r\nA Life if Triumph will inspire you to:\r\n\r\n- Believe in the power within to achieve dreams and goals\r\n- Triumph over negative patterns of thought\r\n- Conquer illness and health issues\r\n- Live with courage and an indomitable spirit\r\n- Find joy and positivity', 'Ryuho Okawa', 'HS Press', '65', 6, 13, 'http://localhost/happykids/uploads/image/A_Life_of_Triumph.jpg', '2021-02-09 12:22:50', 2, '1'),
(2, 'Age of Mercy', 'Truth unites the world. Love ends hatred. Christians, Muslims, and God-believers; Materialists, Communists, and Non-believers.\r\nWhy do they fight? When will they say, \"it\'s all right?\" Ryuho Okawa brings you a messages of salvation from the Primordial God, Who has been nurturing us since the time began.\r\n• Why does this world exist?\r\n• What is the world of truth?\r\n• What are the differences between religions?\r\n• Why do they fight each other?\r\n• God wishes for love and peace on Earth\r\n• There is a Supreme God above all other gods', 'Ryuho Okawa', 'HS Press', '65', 2, 8, 'http://localhost/happykids/uploads/image/Age_of_Mercy.jpg', '2021-02-09 12:26:48', 2, '1'),
(3, 'Art of Business Revitalization', 'In The Art of Business Revitalization: Management Wisdom from Jack Welch, Carlos Ghosn, and Bill Gates, Master Ryuho Okawa conducts spiritual interviews with three of the greatest executives of our time. General Electric\'s Jack Welch, Renault and Nissan\'s Carlos Ghosn, and Microsoft\'s Bill Gates give readers a glimpse into how they took hold of opportunities and turned them into successes. What management philosophies helped Jack Welch and Carlos Ghosn turn around their companies during downturns? What is Bill Gates\'s secret to creating products that become global standards? What human resources management and education philosophies have they drawn upon to keep their companies at the top? This book reveals the secrets to their achievements.', 'Ryuho Okawa', 'HS Press', '55', 2, 4, 'http://localhost/happykids/uploads/image/The_Art_of_Business_Revitalization.jpg', '2021-02-09 12:30:30', 2, '1'),
(4, 'Art of Influence', 'Success often depends on our ability to work with, motivate and inspire people within our sphere of influence. To heighten our reach, Ryuho Okawa introduces 28 key motivations to master the \"art of influence,\" a mindset that surpass entrenched tendencies to become a transformational leader. Become a luminary who can win the hearts of many and inspire meaningful change in both personal and professional life.\r\nAdvice and solutions to such questions as:\r\n• How can I differentiate true confidence from arrogance?\r\n• How should I deal with jealousy and criticism at work?\r\n• How can I gain the support of my coworkers?\r\n• How can I overcome an inferiority complex?', 'Ryuho Okawa', 'HS Press', '50', 0, 3, 'http://localhost/happykids/uploads/image/art_of_influence.jpg', '2021-02-09 12:39:57', 2, '1'),
(5, 'The Basic Teachings of Happy Science', 'Is it possible to consolidate the content of 1,500 books into one? The author of this book, Master Ryuho Okawa is the founder of Happy Science, a religious organization in Japan which has members in more than 100 countries. Since 1985, within a span of around 30 years, he has published more than 1,500 books, an astounding number in countries all over the world and established the fundamental teachings of Happy Science.\r\n\r\nIn this book, the author teaches us what the basic teachings of Happy Science are among the vast amount of teachings he has already given us. However, if one reaches for this book in the hope to read a summary of the 1,500 books, you may realize something much better than expected. In the book, Master Ryuho Okawa says the following:\r\n\r\n\"If the teachings are summarized too rigidly now, there is the possibility that I may become unable to teach the Laws in the future, so I intend to teach what I think is important at any particular time. In this way, I will keep on saying what I have to say without being bound by what I have taught in the past. Although I have been giving lectures for nearly 30 years now, my mission is still not complete. If I continue to do this, I think that our teaching will continue to evolve.\"\r\nRyuho Okawa summarizes the evolving teachings of Happy Science with contemporary examples and perspectives, to excite and inspire audiences anew. Learn why Truth, Faith and Mission that are indispensible to achieve happiness.', 'Ryuho Okawa', 'HS Press', '50', 1, 6, 'http://localhost/happykids/uploads/image/basic_teachings_of_happy_science.jpg', '2021-02-09 12:42:30', 2, '1'),
(6, 'Basics of Exorcism', 'The truth regarding spiritual disturbance and the technique to cope with demons and evil spirits:\r\n• Science and medicine are yet to give answers\r\n• Existing religions give insufficient explanations\r\nNo matter how much time progresses, demons are real. Unhappiness and misfortune in life caused by possession. Spiritual background behind schizophrenia and multiple personality. Spiritual screen against curses - the truth of exorcism as told by the author who possesses the six great supernatural powers - The essence of exorcism as a result of more than 5,000 rounds of exorcist experience!', 'Ryuho Okawa', 'HS Press', '50', 8, 10, 'http://localhost/happykids/uploads/image/basics_of_exorcism.jpg', '2021-02-09 12:44:55', 2, '1'),
(7, 'Challenge of Enlightenment', 'Ryuho Okawa is known for his wisdom, compassion and commitment to educating people to think and act in spiritual and religious ways. Through his Institute for Research in Human Happiness (IRH) he teaches and ministers to people who need help and they in turn spread his teachings to others.\r\n\r\nThe Challenge of Enlightenment presents Okawa&amp;#039;s thoughts on Enlightenment; what it is, what it is not, and the place of happiness and peace in the modern world. He also discusses how to gain enlightenment, and how this links in with other tenets of the Buddhist way of life.\r\n\r\nPresenting the nature of enlightenment and the challenge of attaining it in clear, simple but thought-provoking language, this is an excellent companion to The Essence of Buddha and The Challenge of the Mind, and offers the general reader a complete demystification of an often over-complicated tradition.', 'Ryuho Okawa', 'HS Press', '50', 2, 2, 'http://localhost/happykids/uploads/image/Challenge_of_enlightment.jpg', '2021-02-09 12:50:19', 2, '1'),
(8, 'Decision Towards Prosperity', 'Trump Revolution is a term also used by other authors, not just Ryuho Okawa, but he is one of the authors who see through the essence of this revolution the most. How so? Okawa foresaw the birth of President Trump, as early as in January 2016.\r\n\r\nOkawa, a Global Visionary, clearly sees where the world is headed and how the people in each country should think and act for the world to enjoy a better future. As the opinions by experts on American politics or international politics are in disarray, you could say that this book has pointed out the principal pillar of thought.\r\n\r\nIn the book, Okawa talks a lot about Japanese politics as Japan is his mother country, but the universal philosophy behind his words will surely enlighten readers in other countries too. This is the guidebook that will help the world realize prosperity for the next 300 years.', 'Ryuho Okawa', 'HS Press', '50', 1, 9, 'http://localhost/happykids/uploads/image/decision_towards_prosperity.jpg', '2021-02-10 12:34:31', 2, '1'),
(9, 'The Challenge of The Mind', 'Enlightenment is not an abstract concept, but a state of mind that we all can achieve through diligent and mindful practice! In this modern introduction to the essential teachings of the Buddha, Ryuho Okawa frames how to integrate wisdom and compassion to nurture harmonious living and advance spiritual awareness. Presenting the essential tenets of cause and effect, meditation, transcendental wisdom, egolessness, the middle way, the relationship between enlightenment and spiritual ability, and the nature of karma, The Challenge of the Mind is a comprehensive guide to timeless Buddhist teachings.\r\nLearn essential Buddhist teachings of:\r\n• The Law of Cause and Effect - an essential perspective for understanding how the seeds you sow affect the course of your life?\r\n• Transcendental Wisdom - the practice of moving beyond judgments of good and evil to practice compassion\r\n• Egolessness - a positive state of mind that gives you inner strength to overcome pain and attachments and manifest your true self?\r\n• The Middle Way - a practice of avoiding suffering-causing extremes to harmonize your mind', 'Ryuho Okawa', 'HS Press', '69', 8, 2, 'http://localhost/happykids/uploads/image/Challenge_of_the_mind.jpg', '2021-02-10 12:44:20', 2, '1'),
(10, 'The Essence of Buddha', 'Ryuho Okawa introduces a contemporary interpretation of the way to enlightenment, written by a revered spiritual leader. The fundamental tenets of the Buddhist understanding of life, such as The Eightfold Path, The Six Paramitas and the Laws of Causality, are clearly explained in modern and accessible terms.\r\nEnlightenment is accessible to every sentient being! The path involves an expansion of consciousness to subdue material concerns to heighten spiritual awareness. By offering a new perspective of core Buddhist teachings, Okawa distills a way of life to nurture self-growth and compassion.\r\nIn this book, you will learn about:\r\n• The Story: Shakyamuni\'s inner journey to enlightenment and how he discovered his calling\r\n• The Eightfold Path: a guide to self-reflection and inner discovery\r\n• The Six Paramitas: a guide to mindful and constructive living\r\n• The Void: a spiritual essence that liberates us from material constructs\r\n• The Law of Causality: a way of seeing our past, present and future to self-reflect\r\n• The Path to Enlightenment: a way of life to attain perfection and lifelong compassion', 'Ryuho Okawa', 'HS Press', '90', 6, 2, 'http://localhost/happykids/uploads/image/essence_of_buddha.jpg', '2021-02-10 12:51:06', 2, '1'),
(11, 'On Carbon Footprints Reducing: Why Greta gets angry?', 'September 2019. Greta Thunberg, a 16-year-old environmental activist from Sweden, gave a speech at the United Nations Climate Actions Summit that shocked the world. Ryuho Okawa, Master and CEO of Happy Science Group, felt there was something \"more\" to her expression and words through his spiritual intuition. In this book, Okawa summons the spiritual beings who have influence on Greta, and has them speak their true intention as to why they made her say what she said.\r\n\r\nWhat we found was slightly disturbing, to say the least. Of the two spirits sending inspiration to Greta\'s speeches and activities, one was the spirit of a historical figure involved in the Russian Revolution. Moreover, we found the political motive behind the global warming theory: to put a stop to the industries and economic activities of advanced countries, thereby sapping their power of influence in the international community.\r\n\r\nWe should not be fooled by \"a communism revival movement\" disguised as science. We must not bring our civilization to decline. This is not a matter of \"climate justice,\" but \"world justice.\" We hope this book will inform you of the justice that the world requires today.', 'Ryuho Okawa', 'HS Press', '49', 3, 5, 'http://localhost/happykids/uploads/image/carbon_footprint.jpg', '2021-02-10 12:54:52', 2, '1'),
(12, 'The Importance of the Exploration of the Right Mind', 'The basic teaching of Happy Science is The exploration of the Right Mind. The significance of this book is in that it covers the exploration of the Right Mind for the citizen based on a macro-perspective understanding, with whom true sovereignty lies, in addition to the way to explore the Right Mind for the individual religious practitioner.\r\n\r\nThe macro-perspective that Master Okawa mentions in this book is mainly about the historical recognition after World War II. Master states, \"In fact, there was an aspect to the last war as a \'revolution\' to put an end to white supremacy and create a society where blacks, Asians and Caucasians were fundamentally equal. We must not forget this aspect.\"\r\n\r\nIt is not just about Japan. Master states as follows:\r\n\r\n\"From an international perspective, I think that it is unfair to report the Japanese Prime Minister\'s visit to Yasukuni Shrine as if it were a ceremony to bring back the devil.\" He also makes a proposal: \"America is the world\'s most powerful country, but as a consequence of its power, it needs to think about an accurate view of history, and it is important that it takes a good look at itself. By doing this, it could probably extinguish the hatred which stems from different views of history held by Asian countries, which could spark future war.\"\r\nThis is a must-read book in which Master delivers the true historical perception and God\'s justice on a global scale, and teaches the Right Mind for humankind from 2014 onward.', 'Ryuho Okawa', 'HS Press', '40', 1, 9, 'http://localhost/happykids/uploads/image/exploration_of_right_mind.jpg', '2021-02-10 13:00:40', 2, '1'),
(13, 'For the Love of the Country', 'This year, 2015, makes 70 years since the end of WWII. Now is the time to ask, \"Is it correct to interpret the Pacific War as a war that fascist Japan lost to democratic America?\" What was the true reason for Japan going into WWII? What was Japan trying to accomplish? What kind of influence did Japan have on world history by fighting in the war?\r\n\r\nIn For the Love of the Country, the spirit of Colonel Kunio Nakagawa, garrison commander of Peleliu Island, tells us the untold story of the historical battle between the U.S. Marine Corps and the Japanese forces via spiritual interview conducted by Master Ryuho Okawa of Happy Science. This approach is one method of \"religious journalism.\"\r\n\r\nFor the Love of the Country is a phrase taken from the spiritual messages of Colonel Nakagawa. His deep and sublime love was surely not inferior to that of the U.S. soldiers. We would like you to read this book carefully, page by page, word by word, and listen to your inner voice. The colonel\'s strong sense of love will definitely touch your heart.', 'Ryuho Okawa', 'HS Press', '41', 2, 4, 'http://localhost/happykids/uploads/image/For_the_love_of_country.jpg', '2021-02-10 13:03:16', 2, '1'),
(14, 'Guideposts to Happiness', 'Happiness and unhappiness are determined by the images we hold in our minds. Those who are surrounded by worries or seized by feelings of unhappiness continually hold unhappy images of themselves in their minds. In this book, author and spiritual leader Ryuho Okawa describes in detail some of the negative patterns of thinking that keep us from attaining peace of mind. He outlines the causes of a number of life\'s problems, including depression, inferiority complexes and conflicts that result from over-assertiveness. In this book, you will find many hints to help you solve your worries and attain true happiness.', 'Ryuho Okawa', 'HS Press', '35', 7, 3, 'http://localhost/happykids/uploads/image/guidepost_to_happiness.jpg', '2021-02-10 13:07:50', 2, '1'),
(15, 'On Happiness Revolution', 'Since 2010, Master Ryuho Okawa has published over two hundred spiritual messages, in Japanese, from the spirits of historical men and women and the guardian spirits of today\'s living figures. With this Spiritual Interview Series, Master Okawa is now making these important messages available in English. The books in this series are messages from the spirits or guardian spirits of people who have a great deal of influence over world affairs. These messages reveal these powerful figures\' hidden intentions and disclose facts that even news reporters would have difficulty drawing out. Master Okawa\'s in-depth analyses of these messages give us the tools that we need to understand and confront the dangers that lie ahead of us. Master Okawa hopes to show readers that the spirit world and spirits are real, and that by understanding spiritual truths, we can bring a peaceful end to international conflicts and create solutions to a variety of global crises.', 'Ryuho Okawa', 'HS Press', '35', 1, 4, 'http://localhost/happykids/uploads/image/on_happiness_revolution.jpg', '2021-02-10 13:10:08', 2, '1'),
(16, 'The Heart of Work', 'We all can revitalize ambition to heighten joy and success in our special calling!\r\nSuccess at work can bring great joy, but we find true delight when our tasks are imbued with passion and purpose. When we live our calling, we can carry on through thick and thin, because we know that our work brings value to others and nurtures intrinsic satisfaction. Ryuho Okawa introduces 10 keys to infuse purpose, value and wholehearted devotion to mastering our professional aspirations.\r\nDiscover the keys to:\r\n• Outstanding work\r\n• Career advancement\r\n• Develop a leadership mindset\r\n• The power of rest and relaxation\r\n• Unleash your true potential\r\n• Enduring health and vitality', 'Ryuho Okawa', 'HS Press', '40', 3, 3, 'http://localhost/happykids/uploads/image/the_heart_of_work.jpg', '2021-02-10 13:14:16', 2, '1'),
(17, 'The Hell You Never Knew', 'The conventional image of Hell is a place of eternal suffering where souls are made to suffer. Through remarkable spiritual discovery, Ryuho Okawa re-introduces Hell as a temporary abode for souls to undergo spiritual training and correct lifelong mistakes to earn salvation.\r\nOkawa offers a detailed account of the nine different types of Hell and describes the thoughts and deeds that connect to these realms. According to Okawa, modern ideals are a mishmash of misused freedoms that inevitably lead to poor choices. The purpose of religion is to guide souls away from harmful attenuations, but as ideologies clash, Hell continues to flourish. Knowing that actions have consequences, embrace true salvation of your soul through constructive and mindful living.\r\nAvoid falling prey to Hell by learning:\r\n• How fear brings suffering in this world and into the next\r\n• The vital importance of controlling negative thoughts while alive\r\n• The three modes of thoughts that will guarantee a painful afterlife', 'Ryuho Okawa', 'HS Press', '50', 8, 10, 'http://localhost/happykids/uploads/image/the_hell_you_never_knew.jpg', '2021-02-10 13:28:30', 2, '1'),
(18, 'In Love with the Sun', 'After 600 million years, people shall know the true genesis. Through reading this book, you will see the magnificent scale of El Cantare\'s Law.\r\n• The true story when the earth was born\r\n• The guiding concept of the earth\r\n• The mechanism of creating life on Earth\r\n• And the future that human beings has to seek\r\n• These secrets are now revealed by the spiritual message from Goddess Gaia\r\n• Who supported the creation of Earth civilization by Alpha, the God of origin', 'Ryuho Okawa', 'HS Press', '61', 1, 4, 'http://localhost/happykids/uploads/image/in_love_with_the_sun.jpg', '2021-02-10 13:34:23', 2, '1'),
(19, 'Into the Storm of International Politics', 'In September 2013, President Obama stated, \"We should not be the world\'s policeman.\" As signified by those words, America has been declining and the world order is being lost. In the Middle East, Islamic State declared independence in June 2014. Furthermore, in Hong Kong, the Umbrella Revolution - a movement against China\'s anti-democratic, single-party dictatorship - broke out in September 2014.\r\n\r\nAt the roots of these three movements lie three different sets of values. America\'s decline indicates Christian civilization not having clear standards on what justice is in this complex world of the current era. The problem with Islamic State is that a portion of Muslims in the current era have lost the spirit of peace and tolerance that Muhammad taught. Totalitarianism of China is founded upon materialism, a thought which denies human dignity and freedom of the individual. The world is now seeking a new idea or a new philosophy that will show the countries with such values the direction they should head in.\r\n\r\nMaster Ryuho Okawa is an author of over 1,700 books and spiritual leader with passionate followers in over 100 countries around the world. In this book, Okawa presents new standards of the world order while giving his own analysis on world affairs concerning the U.S., China, Islamic State and others. He does so based on his deep knowledge in world history, world philosophy and world religions as well as his experience in the international trade industry, and also based on his spiritual insight into the hidden consciousness of major countries\' leaders in the current era. In Into the Storm of International Politics, Okawa states:\r\n\r\n\"Some kind of new standard or direction that the world should take needs to be clearly defined. This new direction has to be a moral philosophy to create a new world order and that moral philosophy must include economic principles. Accordingly, it must be a moral philosophy that stimulates global economic growth under the perspective of world justice.\"\r\n\"A new world order should head in this direction\" - a new philosophy from Japan will point to and show us the way.', 'Ryuho Okawa', 'HS Press', '61', 1, 9, 'http://localhost/happykids/uploads/image/into_the_storm_of_international_politic.jpg', '2021-02-10 13:39:48', 2, '1'),
(20, 'Invincible Thinking', 'When we encounter adversity, hardship or failure, how can we find the resilience and will to persevere? It is our mental attitude that determines whether we can realize continuous growth and joyful achievement in any circumstance.\r\nRyuho Okawa\'s philosophy of Invisible Thinking is the dynamite that lets us open a crack of possibility in a mount of difficulties; the powerful drill that lets us tunnel through the solid rock of complacency and defeatism. A mindset of incivility is your most powerful took to transform circumstance into wisdom and soul growth. Invincible Thinking will give you the all the nourishment that you will ever need to fulfill your purpose in life.\r\nIn this book, you will find:\r\n• Essential attitude for overcoming adversity\r\n• Practical lessons to balance mental and physical well-being\r\n• Essential principles for building wealth\r\n• Key attitudes that attract influential people\r\n• Key elements for succeeding in business\r\n• Leadership qualities to guide you and others to success', 'Ryuho Okawa', 'HS Press', '35', 2, 3, 'http://localhost/happykids/uploads/image/invincible_thinking.jpg', '2021-02-10 13:44:56', 2, '1'),
(21, 'Invitation to Happiness', 'Accept your invitation to joyful and authentic living. This beautifully ornate book presents practical tools for creating new habits to live a more a carefree, grounded, spiritual life. Through 7 inspirations, you will be guided to the angel within you - the force that supports you to be courageous, inspired and true to yourself. You will find all the tools that you need to live more confidently, peacefully and authentically.\r\nThere are so many beautiful reasons to be happy!\r\n• Easy-to-use practices for introspection\r\n• Brief, guided visualizations\r\n• Journal space for recording inspirations from your inner angel\r\n• Tips for contemplation\r\n• Simple step-by-step action plans', 'Ryuho Okawa', 'HS Press', '35', 2, 3, 'http://localhost/happykids/uploads/image/invitation_to_happiness.jpg', '2021-02-10 13:46:52', 2, '1'),
(22, 'The Laws of Bronze', 'The Laws of Bronze: Love One Another, Become One People is the 25th volume of Ryuho Okawa\'s renowned Laws Series. This entry underscores the potency of spiritual faith as the purest salve to mend societal divides.\r\nComprised of five lectures that Ryuho Okawa gave in 2017 and 2018, the interwoven theme defends the preservation of faith in the age of technological superiority and exposits that individuals, from all walks of life, can overcome differences through a sincere practice of faith. When we discover our common spiritual origin revealed herein, we will unite as one people, bound by mutual love and appreciation.\r\nAdditional themes explored in this text:\r\n• The virtue of living by spiritual values at the cost of self-sacrifice\r\n• Finding balance between faith and work\r\n• The significance of preserving freedom, democracy and faith\r\n• Create harmony in personal relationships through love', 'Ryuho Okawa', 'HS Press', '65', 1, 12, 'http://localhost/happykids/uploads/image/laws_of_bronze.jpg', '2021-02-10 13:49:33', 2, '1'),
(23, 'The Laws of Courage', 'As a prominent spiritual leader with a diverse background Okawa, originally a successful businessman before awakening to his true calling, provides hands-on guidance for the important lessons that life teaches all people, including friendship and attitude changes in close relationships, as well as broader themes about the global perspective of Right and Wrong, how to find providence in failures, and the ultimate truth about human existence. This practical yet eye-opening book shows how we can find and develop courage within our own being. In order to discover strength and confidence to open a future for ourselves as well as for the world, Okawa espouses both the spirit of self-help and the value of faith. He emphasizes the importance of making efforts and introduces the Law of Compensation, which says that the compensation of what you pay for is equivalent to the value of what you will gain.\r\n\r\nOkawa also reveals the secret of the Cosmic Tree in Chapter 5, Live a Life of Truth. Okawa says that human beings are spiritually all part of a single tree in the Universe and are like travelers visiting this Earth for a limited period of time to learn new lessons and obtain new knowledge through numerous reincarnations.\r\n\r\nHe also introduces a unique perspective on soul mates: when you look at your previous lives, the people you are having complications or conflicts with in this life are actually people that have been in many different relationships with you throughout various reincarnations. In your life training, there are people who you are required to meet... The people you have close relationships with are all connected to the same branch of the Tree of Life. It is a sin to hate or loathe each other... because you would be loathing, damaging, and trying to cut off another branch that is connected to the same bough of life as you. In many cases, the person that you despise or hate has an extremely deep spiritual tie with you, and is someone you have met many, many times in your previous lives. He states that the realization of this truth is the key to solving hatred and conflicts that plague the world today.\r\n\r\nThis latest book by Okawa was made available in English to celebrate the publishing of his 501st book.', 'Ryuho Okawa', 'HS Press', '35', 11, 3, 'http://localhost/happykids/uploads/image/laws_of_courage.jpg', '2021-02-10 13:52:40', 2, '1'),
(24, 'The Laws of Faith', 'Since antiquity, religion has played a pivotal role in human development. Faith is the anchor of the mind; however modern systems of thought favor logical reasoning, leaving many to stray away from spiritual progress. A likely cause of this deficit is the failure of traditional religions to provide concise answers to modern questions. Ryuho Okawa preaches at the core of a new universal religion, that aligns logical and spiritual reasoning with contemporary events and modes of thought. Learn to champion diversity and mend differences in ethnicity, religion, race and gender, to harmonize nations towards an era of peace and prosperity.\r\nAdditional themes explored in this text:\r\n• What breeds conflict of faith?\r\n• Why does God permit war and poverty?\r\n• Why does discrimination exist?\r\n• Did God abandon humanity?\r\n• What is God\'s justice?', 'Ryuho Okawa', 'HS Press', '65', 12, 8, 'http://localhost/happykids/uploads/image/laws_of_faith.jpg', '2021-02-10 13:56:32', 2, '1'),
(25, 'The Laws of Great Enlightenment', 'Persistent blame for past mistakes, setbacks, failures and strained episodes of reconciliation are inner pains that vibrate distress. Through the power of \"Enlightenment,\" which Ryuho Okawa presents in a contemporary format, we can mute echoes of anguish by learning to forgive ourselves, others and harmonize our emotions through mindful practice.\r\nOkawa teaches how to govern our minds and regain our true nature as spiritual beings. According to Okawa, through the practice of self-reflection, meditation and prayer, we can attune to the \"Great Universe\" to become one with the \"Great Being.\" In this way, we can enjoy a liberated and peaceful state of mind, regardless of circumstance. Learn to balance spirituality and worldly skills to strengthen our influence to bring happiness to many.\r\nAs you progress, learn how to:\r\n• Use the power of forgiveness from a Buddhist perspective\r\n• Free your soul from constant inner turbulence with the \"Power of Wisdom\"\r\n• Discover the misinterpretation of Zen Enlightenment and the relationship between skill and attaining enlightenment\r\n• Master the \"Laws of the Mind\" throughout life\r\nLet wisdom and compassion be your compass to always walk with the Buddha.', 'Ryuho Okawa', 'HS Press', '60', 2, 2, 'http://localhost/happykids/uploads/image/laws_of_great_enlightment.jpg', '2021-02-10 14:01:41', 2, '1'),
(26, 'The Laws of Happiness', 'The Laws of Happiness: Love, Wisdom, Self-Reflection and Progress is the eighth volume of Ryuho Okawa\'s celebrated Laws Series, commencing with 1994\'s The Laws of the Sun, and endeavors to answer the question, \"What is true happiness?\" This milestone text introduces four distinct principles, based on the \"Laws of Mind\" and sourced from Okawa\'s real-world experience, to guide readers towards sustainable happiness. Okawa\'s four \"Principles of Happiness\" present an easy, yet profound framework to ground this rapidly advanced and highly competitive society. In practice, Okawa outlines pragmatic steps to revitalize our ambition to lead a happier and meaningful life.\r\n\r\nIn Chapter One, to counter states of unhappiness, Okawa reveals the two important purposes of life and encourages readers to nurture a mindset that pledges to turn weakness (negative tendencies) into strength (positive tendencies). Once we accept life\'s two purposes, we can change the course of life and overcome bouts of unfavorable destiny through our own diligent effort, regardless of circumstance.\r\n\r\nChapter Two elucidates the importance of nurturing happiness in the workplace, while kindling professional aspirations. Okawa introduces practical steps to improve work- life balance and navigate stressful activity without sacrificing peace of mind. Okawa underscores the importance of finding a mission at work, and outlines steps to improve our skills, with tips to boost self-planning and time management efficacy.\r\n\r\nChapters Three and Four offer an in-depth exploration of Okawa\'s Principles of Happiness - Love, Wisdom, Self-Reflection, and Progress, with recommendations on how to apply them in daily personal relations.\r\n\r\nChapter Five introduces the ideal world that Okawa aspires to create, based on concepts introduced in his landmark text, The Laws of the Sun. According to Okawa, through individual effort to progress in concert with the \"Four Principles of Happiness,\" we can collectively harmonize to bring forth a new age - coined by Okawa as \"The Age of the Sun,\" where humanity thrives in peace and prosperity.', 'Ryuho Okawa', 'HS Press', '69', 1, 3, 'http://localhost/happykids/uploads/image/laws_of_happiness.jpg', '2021-02-10 14:03:12', 2, '1'),
(27, 'The Laws of Hope', 'The Laws of Hope: The Light is Here provides ways to bring light and hope to ourselves through our own efforts, even in the midst of sufferings and adversities. Inspired by a wish to bring happiness, success, and hope to humanity, Okawa shows us how to look at and think about our lives and circumstances. He says that hopes come true when we have the right mindset inside us. When we feel depressed, happiness cannot be easily gained by competing with others, but there is limitless potential for growth when we are in competition with ourselves. Sometimes, we should also praise ourselves more.\r\nThe Laws of Hope describes not just worldly ways to make your hopes come true, but also an inner, spiritual kind of success. It is the kind of success that does not come from only sacrificing yourself for others\' sake or the reverse. It leads to everyone\'s happiness. It also leads you to become an invincible, reliable leader with a bird\'s-eye view of long-term victory and a heart that thinks of others. By making these kinds of efforts in your current circumstances, you can fulfill your mission to shed light on yourself and those around you.\r\nIn this book you will learn:\r\n• What kind of mindsets are necessary to achieve your dreams and hopes?\r\n• How can we overcome a negative self-image and depression?\r\n• What are \"The Laws of Success\" that are not taught in contemporary education?\r\n• What is the meaning and mission of our lives in this world?', 'Ryuho Okawa', 'HS Press', '20', 1, 8, 'http://localhost/happykids/uploads/image/laws_of_hope.jpg', '2021-02-15 11:53:33', 2, '1'),
(28, 'The Laws of Invincible Leadership', 'Today\'s society has become increasingly competitive, posing a myriad of work-life challenges and workplace stigmas.\r\n\r\nThe Laws of Invincible Leadership distills Ryuho Okawa\'s 30+ years of organizational leadership into a management mindset that nurtures bilateral success in personal and professional life. Okawa\'s breakthrough cross-functional approach is universally applicable to all who aspire to become invincible leaders in their respective field or span of influence. Let Okawa\'s enthusiasm for continuous growth and development inspire you to become invincible in enterprise (and in life) to reach new heights of success.', 'Ryuho Okawa', 'HS Press', '20', 1, 11, 'http://localhost/happykids/uploads/image/laws_of_invincible_leadership.jpg', '2021-02-15 11:55:45', 2, '1'),
(29, 'The Laws of Justice', 'How can we resolve conflicts in this world? Why do we live in constant turmoil, when we strive for peace? By contemplating this macro-view, it elevates our awareness to appreciate our divine nature and percieve our interconnectedness with God. Ryuho Okawa bestows an enlightened perspective that peers beyond religious, political, societal, economic and academic disparities to mend the ambiguities of worldly conflict and reinforce God\'s infinite love.', 'Ryuho Okawa', 'HS Press', '20', 5, 12, 'http://localhost/happykids/uploads/image/laws_of_justice.jpg', '2021-02-15 11:58:22', 2, '1'),
(30, 'The Laws of Mission', 'In this day of advanced scientific reasoning, are we deluded by a false sense of awareness?\r\n\r\nRyuho Okawa presents integral spiritual truths to mitigate turmoil fueled by atheism, skepticism and religious misunderstanding. Okawa\'s inspiring message imparts pivotal breakthroughs to seed spiritual awareness across diverse provinces and champions the acceptance of spiritual development in a seemingly secular age.', 'Ryuho Okawa', 'HS Press', '25', 3, 12, 'http://localhost/happykids/uploads/image/laws_of_mission.jpg', '2021-02-15 12:00:38', 2, '1'),
(31, 'The Laws of Perseverance', 'I have cited many examples from the four great saints - Shakyamuni Buddha, Jesus Christ, Socrates and Confucius - to Jan Hus, Joan of Arc, Lincoln and Shoin Yoshida. People who have left their mark on history did not necessarily sail smoothly through their lives. No matter how much you suffer, the Truth will gradually shine forth as you continue to endure hardships. Therefore, simply strengthen your mind and keep making constant efforts in times of endurance, however ordinary they may be. Eventually, you will come out of your slump and overcome your hardships. And, as you try and aim to reverse the common sense, you will one day understand that people can be \"undefeated\" even if they seem to have lost in this world. In that process, you may sometimes feel that virtue is being generated. We have already gone beyond the limits of the common sense of this world. All we can do is to keep fighting with an indomitable heart.', 'Ryuho Okawa', 'HS Press', '25', 5, 12, 'http://localhost/happykids/uploads/image/Laws_of_Perseverance.jpg', '2021-02-15 12:15:59', 2, '1'),
(32, 'The Laws of Success', 'The Laws of Success is a modern guide to happiness and success in all facets of life. In these pages, you will find timeless wisdom for living with purpose and hands-on advice to heighten thresholds of joy at home and satisfaction in the workplace. Ryuho Okawa introduces 8 powerful principles to actualize hope, guard from setbacks and live prosperously, to foster enduring and sustainable happiness.\r\nIn this book, you will find:\r\n• A unique perspective on how to attain purposeful, joyful success\r\n• The mindset for cultivating an aura of success\r\n• Maintain a positive attitude during setbacks\r\n• Principles for achieving success in business and leadership\r\n• Essential conditions for ongoing prosperity\r\n• Wisdom to help you gain mastery over your thoughts\r\n• Harness your inner potential to achieve self-realization', 'Ryuho Okawa', 'HS Press', '25', 7, 3, 'http://localhost/happykids/uploads/image/laws_of_success.jpg', '2021-02-15 12:19:06', 2, '1'),
(33, 'The Laws of the Sun', 'Why and how did God create this world? What are the universal spiritual laws that shape this world and how can we learn to love in harmony with them? What is the nature of spirit and soul? For what purpose are we born, and now can we find true happiness and meaning in life?\r\n\r\nIn The Laws of the Sun, Ryuho Okawa, based on his miraculous ability to see the past, present and future, answers these essential questions by offering his remarkable account of the framework of the \"Laws\" that govern the universe. Okawa explains how and why the Creator designed the universe and all matter, and shows us how living in accord with the Truths gives us the power to change our loves and transform our planet - turning away from catastrophe, toward love and acceptance between people of all religions and races.\r\n\r\nWhen Jews, Christians, Muslims and Buddhists alike discover their common spiritual source, their hearts will be inspired to let go of millennia of conflict and finally forgive and embrace one another. As we come together as one people from one source on one planet, we will build a new era of spirituality based on the Truths, as they are revealed in this transformative book.', 'Ryuho Okawa', 'HS Press', '30', 3, 12, 'http://localhost/happykids/uploads/image/laws_of_sun.jpg', '2021-02-15 12:20:58', 2, '1'),
(34, 'The Laws of Wisdom', 'The Laws of Wisdom guides you along the path on how to acquire wisdom, so that you can break through any wall you are or will confront in your life or in your business. By reading this book, you will be able to avoid getting lost in the flood of information and, going beyond the level of just amassing knowledge, be able to come up with many great ideas, make effective planning and strategy and develop your leadership while receiving good inspiration.\r\nLet\'s all break through walls, open up a path and create a bright future!\r\nContents included in The Laws of Wisdom:\r\n• Ways to transform information into knowledge and knowledge into wisdom\r\n• Requirements to receive good inspiration\r\n• Art of working to produce intellectual output and the secrets to create new added values\r\n• Setting aside 90 minutes a day for your intellectual pursuit\r\n• Gain a new perspective by becoming proficient in a foreign language\r\n• The power of mind that defeats negative thinking\r\n• Your academic background gives you no advantage after ten years of working in society\r\n• A leader is someone who knows what he or she must do\r\n• Two conditions to motivate people and expand your business', 'Ryuho Okawa', 'HS Press', '20', 2, 3, 'http://localhost/happykids/uploads/image/laws_of_wisdom.jpg', '2021-02-15 12:22:47', 2, '1'),
(35, 'HS Press  Higher Education  Learning the Spirit of the Founder of Happy Science University Part I (Overview)', 'Happy Science University (HSU) is a religious institution for higher education, founded with an aim to create a new civilization. The founder, Master Ryuho Okawa, passionately talks about the founding spirit of HSU and the challenge of religious Truth. He aspires to reorganize academic discipline based on a religious spirit and create a bright future for both Japan and the world.', 'Ryuho Okawa', 'HS Press', '15', 2, 6, 'http://localhost/happykids/uploads/image/learning_the_spirit_of_the_founder_of_HS.jpg', '2021-02-15 12:25:47', 2, '1'),
(36, 'Love for the Future', 'Love for the Future: Building One World of Freedom and Democracy Under God\'s Truth is a compilation of select international lectures given by Ryuho Okawa during his (ongoing) global missionary tours. While conflicting values of justice exists, this book espouses that freedom and democracy are vital principles for global unification that will resolutely foster peace and shared prosperity. The culminating reason - these principles are based on a belief in \"God\'s Love\" and that we all contain divine nature within.\r\nThe new catalyst for humanity is to accept the universal spiritual Truths under which we all live:\r\n• The inherent dignity of all people\r\n• God\'s Wisdom can resolve global conflict\r\n• God\'s Love extends to every person, beyond race, nationality and religious ideology\r\nThe \"Love of God\" watches over politics, philosophes and religions - it is the coalescing force that will lead humanity towards a prosperous future. With this insight, Okawa urges freedom, democracy and faith to stand as the three pillars to individual happiness and world peace.', 'Ryuho Okawa', 'HS Press', '25', 8, 8, 'http://localhost/happykids/uploads/image/love_for_the_future.jpg', '2021-02-15 12:35:00', 2, '1'),
(37, 'Love, Nurture, and Forgive', 'Ryuho Okawa reveals the secrets of spiritual growth based on his own real life experiences. Starting from practicing the \"love that gives,\" instead of expecting something in return for what you have done to help others, you can experience a remarkable transformation through your own self-help efforts to develop through the stages of love.', 'Ryuho Okawa', 'HS Press', '35', 4, 8, 'http://localhost/happykids/uploads/image/love,nurture_and_forgive.jpg', '2021-02-15 12:38:09', 2, '1'),
(38, 'The Manifesto of the Happiness Realization Party', 'Happy Science, a new religion representing modern-day Japan, is working to realize &quot;the happiness that carries over from this world to the next.&quot; Not only is Happy Science helping people return to Heaven after death, but it is also trying to make this world, a training ground for the soul, a place where people can live shining brightly.\r\n\r\nIn order to strongly promote the creation of such a world, Master Ryuho Okawa of Happy Science established the Happiness Realization Party in May 2009, a new political party to take on that task. This book is the declaration of the establishment of HRP by Master Okawa. The title of this book may remind you of Communist Manifesto which was written by Karl Marx back in 1848. In The Manifesto of the Happiness Realization Party, the author states the following:\r\n\r\n&quot;As a result of Communist Manifesto, humanity suffered for a period of over 150 years. Ultimately, this became an experiment on civilization that brought about the creation of materialist nations, and thus &#039;Manifesto of the Happiness Realization Party&#039; is aiming to achieve the opposite of this. The &#039;Manifesto of the Happiness Realization Party&#039; declares, &#039;We shall mobilize the capacities of people who recognize the existence of God and Buddha and believe in the correct Buddha&#039;s Truth, and work to build a worldly, realistic utopia. We shall make Japan a starting point for our political activities, and have an impact on people throughout the whole world. We intend to bring about a simultaneous global revolution in the correct sense.&#039;&quot;\r\nThis book is a historical declaration to change the world through a peaceful revolution by the philosophy and speech based on the Truth, rather than by violence or massacre. The book states the political issues of modern-day Japan, which is the birthplace of such revolution; it also states on the assessment of the meaning of WWII as well as how the relation between religion and politics should be. It is a must read for all people who wish to build a true utopia.', 'Ryuho Okawa', 'HS Press', '20', 6, 9, 'http://localhost/happykids/uploads/image/manifesto_of_the_happiness_realization_party.jpg', '2021-02-15 12:45:22', 2, '1'),
(39, 'Messages from Heaven', 'In Messages from Heaven: What Jesus, Buddha, Moses and Muhammad Would Say Today, Ryuho Okawa reveals the spiritual communication that he had with these four divine spirits and the messages that they wish to share with society.\r\n\r\nThese spiritual messages present diverse perspectives on faith. Jesus shares messages of love, faith and forgiveness; the Buddha discusses perseverance, success and enlightenment; Moses explores the meaning of righteousness, sin and justice; Muhammad answers questions about tolerance, faith and miracles.\r\n\r\nThis book is proof of God \'s great love for humanity; it proves that He embraces the different views and ideas of diverse religions. Through conversations with the four divine messengers of God, Okawa explores the universal Truths that are common to all faiths to mend religious differences. Although fundamental Truths never change, a new age requires new ways of understanding them.', 'Ryuho Okawa', 'HS Press', '20', 1, 4, 'http://localhost/happykids/uploads/image/message_from_heaven.jpg', '2021-02-15 12:50:13', 2, '1'),
(40, 'The Miracle of Meditation', 'There is more to meditation than simply sitting quietly and emptying your mind. Meditation can draw forth the self-transformative potential within and connect your soul to the wisdom of Heaven - all through the power of belief. Ryuho Okawa combines the power of faith and the practice of meditation to discover your inner divinity.\r\nWith how-tos and answers to common questions about meditation this insightful guide will awaken your soul to encourage a more mindful and fulfilled life.\r\nIn this book, you will learn to:\r\n• Live with a profound inner awareness\r\n• Understand the purpose and source of problems\r\n• Practice meditation in progressive stages\r\n• Learn new meditations to compliment your mood\r\n• Find the answers to commonalty asked questions', 'Ryuho Okawa', 'HS Press', '25', 2, 2, 'http://localhost/happykids/uploads/image/Miracle_of_meditation.jpg', '2021-02-15 12:52:59', 2, '1'),
(41, 'Miraculous Ways to Conquer Cancer', 'Cancer is curable! Cancer can be conquered! This book reveals how the mind creates cancer and the keys to overcome illnesses:\r\n\r\nThe true nature of cancer\r\nThe mental attitude to fight illnesses\r\nDo internal organs have their own consciousness?\r\nThree effective approaches to recover from cancer\r\nHow to generate healing power\r\nWhat makes miracles happen?\r\nYou will get tips on cancer remedies - knowledge that go beyond the common sense in the field of medicinal science. There are three easy steps that will guide you to prevent or overcome cancer. It also includes various real life cases of Master Ryuho Okawa analyzing the spiritual cause that will give you hints on curing your illness. This book will be a huge eye opener for everyone! Drive out cancer from your life!\r\n\r\n&amp;quot;There is only one truth. Although at a slow pace, human bodies are continuously changing, just like the flow of a river; human bodies cannot remain in the same form. The power of the mind can rebuild your body.&amp;quot;\r\n&amp;quot;Bring back the power to believe. Believe that you can regenerate your own body. Faith is stronger than illness.&amp;quot;', 'Ryuho Okawa', 'HS Press', '20', 12, 8, 'http://localhost/happykids/uploads/image/miraculous_ways_to_conquer_cancer.jpg', '2021-02-15 12:56:02', 2, '1');
INSERT INTO `books` (`id`, `book_name`, `description`, `author`, `publisher`, `price`, `quantity`, `categoryId`, `book_image`, `create_date`, `userId`, `status`) VALUES
(42, 'The Moment of Truth', 'Ryuho Okawa awakens your soul to the hidden memory about your true roots as a child of God. A part of God resides within you. This divine essence provides you with the power to find your own salvation, even amid adversities. Today, people have forgotten an essential truth: that we all have the potential to work as God \'s angels, even as we live on Earth. Okawa shows that we are essentially spiritual beings and that our true and lasting happiness is not found within the material world, but rather in acts of unconditional and selfless love towards the greater world.\r\n\r\nThese pages reveal God \'s mind, His mercy and His hope that many of us will become living angels that shine light into this world. Seek the light within yourself and there you will find God \'s Will, compassion and dream to dispel darkness and issue forth an era of worldwide peace.', 'Ryuho Okawa', 'HS Press', '20', 2, 3, 'http://localhost/happykids/uploads/image/moment_of_truth.jpg', '2021-02-21 12:10:47', 2, '1'),
(43, 'My Journey through the Spirit World', 'What happens when we die? Do Heaven and Hell exist? My Journey through the Spirit World is a detailed guide to what lies beyond our lives. Ryuho Okawa shares his travels to the hereafter and details vivid interactions with the souls who reside there, to answers questions like ...\r\n\r\nWhat worlds exist in the afterlife?\r\nWhat determines where we will go when we die?\r\nWhat should we know before we decide to become an organ donor?\r\nWhat is the purpose of the afterworld?\r\nThe spirit world, Okawa reveals, is not only our destination when we cross, but also a reality that is influencing our lives in this physical world. This guide to afterlife will awaken us to the truth of life and death, to guide our earthly aspirations, so that we may return to the magnificent world of Heaven.', 'Ryuho Okawa', 'HS Press', '26', 2, 4, 'http://localhost/happykids/uploads/image/my_journey_through_the_spirit_world.jpg', '2021-02-21 12:11:52', 2, '1'),
(44, 'The Mystical Laws', 'Life after death, channeling, spiritual possession, occultism, UFOs... Master Ryuho Okawa of Happy Science, author of over 1,800 books, reveals the truths of the great universe.\r\n\r\n\"I believe that once you have finished reading this book, you will find it impossible to return to your old self, for you have now learned the secrets that run through this world and the other. When you have learned of what has been hidden, will you feel guilt or will you find courage welling up from within? Whichever you experience, you can be sure that the train of life you are riding will take a completely new track.\"', 'Ryuho Okawa', 'HS Press', '20', 5, 8, 'http://localhost/happykids/uploads/image/mystical_laws.jpg', '2021-02-21 12:52:19', 2, '1'),
(45, 'The Next Great Awakening', 'The Next Great Awakening begins with a recounting of Okawa\'s personal awakening. He explains why the \"Real World\" is not what we see with our limited senses, and shares \"The Truth\" about alien visitations in this New Space Age. One chapter also consists of verbatim conversations with four Higher Spirits: Enlil, Athena, Confucius and Rient Arl Croud in which they offer sage observations and predictions. In this new book Master Okawa described the New Space Age and one that will ultimately see an influx of alien visitors, an end to war, and the beginning of Utopia on Earth. Okawa convincingly explains why Earth, of all the planets in the Universe, is destined to become the \"Planet of Love,\" and why we must wholeheartedly welcome extraterrestrial beings. Extraterrestrials have in fact long lived among us, Master Okawa reports, with many more preparing to visit. Those here now, and those yet to come will publicly declare themselves once we are able to stop all wars and other forms of violence against each other and against the Earth itself, he writes. Explaining Happy Science, Okawa describes it as a non-denominational religious movement that warmly welcomes all races and creeds. Backing up his claim are the testimonials of followers from around the world, who report that their belief in and commitment to the teachings of Master Okawa allows them to \"experience miracles every day.\"', 'Ryuho Okawa', 'HS Press', '20', 1, 10, 'http://localhost/happykids/uploads/image/great_awakening.jpg', '2021-02-21 12:55:08', 2, '1'),
(46, 'The Next President', 'The Next President: Spiritual Interviews with the Guardian Spirits of Newt Gingrich vs. Mitt Romney vs. Rick Santorum uncovers the honest and true intentions of these three Republican leaders currently in a heated race for the GOP presidential nomination. In three rare spiritual interviews by Happy Science, the guardian spirits of Mr. Newt Gingrich, Mr. Mitt Romney, and Mr. Rick Santorum, speak through Master Ryuho Okawa, in English, to answer questions about what they aim to accomplish if America chooses them as the next President of the United States.', 'Ryuho Okawa', 'HS Press', '20', 1, 9, 'http://localhost/happykids/uploads/image/next_president.jpg', '2021-02-21 12:58:26', 2, '1'),
(47, 'The Nine Dimensions', 'Ryuho Okawa reveals that our souls were made to pursue spiritual evolution. Okawa shows us that God designed this world, and the vast, wondrous world of our afterlife as a school with many levels through which our souls learn and grow. We children of God have the potential for infinite growth as we strive to grow closer to His likeness. In addition to the joys that we derive from our individual progress, God also gave humankind the objective of producing harmony and bravery from the diversity of our collective existence.\r\n\r\nThis is a window into the mind of our loving God, who encourages us to grow into greater angels. It reveals His deepest intentions, answering the timely questions of why He conceived such a colorful medley of religions, philosophies, sciences, arts and other forms of expression. It is His hope that when the religions and cultures of the world discover the truth of their common spiritual origin, they will be inspired to accept their differences, come together under faith in God and build an era of harmony and peaceful progress on Earth.', 'Ryuho Okawa', 'HS Press', '20', 8, 8, 'http://localhost/happykids/uploads/image/nine_dimension.jpg', '2021-02-21 13:01:15', 2, '1'),
(48, 'Tips to Find Happiness', 'Creating a Harmonious Home for Your Spouse, Your Children, and Yourself\r\n\r\nThroughout our lives, various things make us unhappy. Tips to Find Happiness is a series of questions and answers on common problems in marriage, work, and relationships, offering a wide range of both practical and spiritual suggestions that will be sure to resonate with everyone who has experienced difficulties in the home. Spiritual leader Ryuho Okawa clearly explains the root of each problem and breaks down the process for solving it, so that anyone can follow it through. Okawa answers each question with determination and compassion, offering guidance that will enlighten the life of each and every person. Tips to Find Happiness is an inspiring and practical guide that is eminently useful for everyday life.', 'Ryuho Okawa', 'HS Press', '30', 13, 3, 'http://localhost/happykids/uploads/image/Tips_to_find_happiness.png', '2021-02-25 12:08:42', 2, '1'),
(49, 'The Origin of Love', 'Love is what we all admire; it is our ideal. True love is revealed in the beauty and brightness of our souls. Love begins with the idea that we all originated from one God and that we are essentially one with others. Why do people love each other, or hate each other?\r\n\r\nIn this book, spiritual teacher Ryuho Okawa answers this question by referring to the origin of love in relation to the secret of eternal life. When you understand the Truth about love, you will be awakened to the wonder of being given life, and you will be filled with love for those around you.', 'Ryuho Okawa', 'HS Press', '21', 4, 8, 'http://localhost/happykids/uploads/image/the_origin_of_love.jpg', '2021-02-25 12:10:02', 2, '1'),
(50, 'The Philosophy of Progress', 'What is wealth? Is money good or evil? These have been controversial issues and no one ever seems to have answered these simple questions clearly. In this book, Ryuho Okawa provides us with answers on wealth, prosperity, and progress from a perspective based on spiritual truth. He teaches that as long as people hold on to poverty in their minds, they will never become wealthy.', 'Ryuho Okawa', 'HS Press', '21', 2, 8, 'http://localhost/happykids/uploads/image/philosophy_progress.jpg', '2021-02-25 12:13:06', 2, '1'),
(51, 'A Political Revolutionary', 'In this book, the Founder and the Master of Happy Science Group as well as the Father of Happiness Realization Party, Master Okawa lays down the guiding principles and the ways to breakthrough on the topics of economy, finance, nuclear power plant, foreign diplomacy, social welfare, and society with aging population and a falling birth rate.\r\n\r\nThis book reveals the political philosophy necessary in today\'s age of political confusion that can be represented through incidents such as the failure of democratizing movement in the Middle East called Arab Spring, the military coup in Thailand, and the rise of power of non-democratic nation China. A must-read book that is written with all the author\'s might.', 'Ryuho Okawa', 'HS Press', '21', 1, 9, 'http://localhost/happykids/uploads/image/political_revolutionary.jpg', '2021-02-25 12:15:08', 2, '1'),
(52, 'The Royal Road of Life', 'With over thirty years of lectures and teachings spanning diverse topics of faith, self-growth, leadership (and more), author Ryuho Okawa presents the profound Eastern wisdom that he has cultivated on his approach to life. The Royal Road of Life illuminates a path to becoming a person of virtue, whose character and depth will move and inspire others towards the same meaningful destination.\r\n\r\nIn these pages, Okawa frames a way of life to master the mind through developing character, chiseled by dignity, wisdom and morality, while keeping a perspective of spirituality. On this path towards perfection, we will experience lasting and meaningful joy through self-development, says Okawa.\r\n\r\nLet this book be your guide to attainable success and happiness (that is not limited to this existence alone). Learn to cultivate a way of life that will radiate joy and inspire friends, family and colleagues to experience this magnificent journey.\r\n\r\nDiscover Okawa\'s guideposts for purposeful living:\r\n\r\nCultivate unwavering inner peace\r\nBuild inner virtues such as wisdom, trustworthiness and courage\r\nMaster the use of time to enhance and maximize results\r\nAdvice to rebuild your life after failure, setback or adversity', 'Ryuho Okawa', 'HS Press', '16', 1, 8, 'http://localhost/happykids/uploads/image/Royal_road_of_life.jpg', '2021-02-25 12:35:09', 2, '1'),
(53, 'The Reason We Are Here', 'The Reason We Are Here is a book of thought that is unlike any other: its global perspective, timely opinion on current issues, and spiritual class are unmatched. The main content is the lecture in Toronto, Canada given in October 2019 by Ryuho Okawa, a Japanese spiritual leader and the national teacher of Japan. Also included are his answers to the questions - specifically, on the Hong Kong and Uyghur problems - from renowned activists who attended his lecture.\r\n\r\nThe major themes of Okawa\'s Toronto lecture were the suppression of democratic movement in Hong Kong and the human rights suppression of Uyghurs, both of which are acts by totalitarian China and harshly criticized by countries around the world. These are subjects of human dignity, the central concept of religion. Additionally, Okawa talked on the themes of global warming and LGBT, to which none of the world religions today can provide answers. He indicated clear guidelines to deal with these problems from the standpoint of the spiritual truth and from God. In this context, \"God\" refers to the common source, the supreme being in religions such as Christianity, Islam, Judaism, and Buddhism.\r\n\r\nGod wishes for the happiness of all people. That is why He does not stay silent on modern issues, for example, international affairs, environmental concern, and sexual orientation. Realize happy people and happy societies by working together to solve these problems in the name of God\'s justice - that is The Reason We Are Here. So, every human being has the responsibility to learn this fact and study the Truth. We hope you\'d do so.', 'Ryuho Okawa', 'HS Press', '16', 2, 9, 'http://localhost/happykids/uploads/image/reason_we_are_here.jpg', '2021-02-25 13:00:12', 2, '1'),
(54, 'The Science of Happiness', 'The Science of Happiness presents Master Okawa\'s 10 essential principles that can serve as a compass for a spiritual life: Happiness, Love, the Mind, Enlightenment, Progress, Wisdom, Utopia, Salvation, Reflection, and Prayer. Master Okawa shows how following these principles can bring happiness and spiritual growth not only to ourselves but to all those around us. He provides the tools necessary to transform one \'s inner world to be receptive to true happiness and enlightenment--and to find one \'s true purpose in life. He also reveals other extraordinary spiritual truths, such as the secrets of the ancient continents of Mu and Atlantis and the structure of the spirit world.\r\n\r\nPresents the foundational teachings of the Happy Science spiritual movement (more than 10 million members worldwide)\r\nOffers revelations from past spiritual leaders, including Jesus, Buddha, and Moses\r\nIncludes information on the ancient continents of Mu and Atlantis and the structure of the spirit world', 'Ryuho Okawa', 'HS Press', '23', 1, 8, 'http://localhost/happykids/uploads/image/science_of_happiness.jpg', '2021-02-25 13:03:44', 2, '1'),
(55, 'Secrets of the Everlasting Truths', 'Okawa offers a glimpse of the vast universe created by God and discloses that humanity is intimately guided by celestial influences. Our planet will experience a decisive paradigm shift of \"knowledge\" and \"truth,\" culminating in an era of paradoxical spirituality, where mastery of science will depend on spiritual knowledge. The advancement that we seek, resides within us.', 'Ryuho Okawa', 'HS Press', '23', 7, 8, 'http://localhost/happykids/uploads/image/secrets_of_everlasting_truth.jpg', '2021-02-25 13:04:27', 2, '1'),
(56, 'Spiritual World 101', 'The definitive book on the Spirit World! An invitation to spiritual happiness that can continue through this world to the next.\r\n\r\nThis book is a spiritual guidebook that will answer all your questions about the spiritual world, with illustrations and diagrams explaining about your guardian spirit and the secrets of God and Buddha. By reading this book, you will be able to understand the true meaning of life and find happiness in everyday life.\r\n\r\n\"People are born into this world in order to learn something and, after they have done this, they take it back with them to the Real World, to the true world they originally came from.\"', 'Ryuho Okawa', 'HS Press', '21', 21, 8, 'http://localhost/happykids/uploads/image/spiritual_world_101.jpg', '2021-02-25 13:07:02', 2, '1'),
(57, 'The Starting Point of Happiness', 'Ryuho Okawa awakens us to the true spiritual values of our life; he beautifully illustrates how we can find purpose and meaning to attain enduring happiness. Okawa empowers spiritual seekers to find the strength amidst difficult circumstances and to savor the joy of giving love to others - all in accordance with the will of the great universe. This self-renewing guide to positive living will awaken us to spiritual truths that invite authentic and lasting happiness.\r\n\r\nIn this book, you will also find:\r\n\r\nWhat are the two direction of love?\r\nHow can we overcome an inferiority complex through love?\r\nHow we are connected to the source of infinite wisdom?\r\nNew ways of thinking to achieve personal fulfillment\r\nThe truth of life from the perspective of the great universe', 'Ryuho Okawa', 'HS Press', '31', 8, 3, 'http://localhost/happykids/uploads/image/starting_point_of_happiness.jpg', '2021-02-25 13:10:24', 2, '1'),
(58, 'The Strong Mind', 'In the Strong Mind, author Ryuho Okawa presents a self-transformative perspective on life\'s hardships and challenges, as precious opportunities for inner growth. No matter what your circumstances or how slow your progress may seem you will develop the strength of character to rise about the limitations that each stage of life can bring. With this book as your guide, life\'s challenges will become treasures to bring lasting and continuous enrichment for your soul.\r\n\r\nLearn the following mental attitudes to achieve a \"strong mind\"...\r\n\r\nResilience: the mental toughness that empowers you to bounce back from adversity\r\nStoutness: the courage to stand up for and strive to realize that you believe in your heart\r\nInner Maturity: a heart that acknowledges the diverse views and perspectives of people\r\nInner Richness: a noble spirit founded on a strong sense of duty\r\nInner Strength: an unwavering spirit that lets you remain calm and staunch', 'Ryuho Okawa', 'HS Press', '33', 1, 2, 'http://localhost/happykids/uploads/image/strong_mind.jpg', '2021-02-25 13:12:42', 2, '1'),
(59, 'Think Big!', 'All achievements are distilled from a single thought and realized by the courage (and will) to follow through. Ryuho Okawa inspires readers with practical steps to harden determination, cultivate awareness, improve decision making and harness creativity to realize our dreams.\r\n\r\nThink Big! offers the support and encouragement to shift to new ways of thinking and mastery of self-discipline. Okawa\'s self-proven approach fosters stability and strength to overcome the diverse challenges that we face. Put into practice, this powerful method will motivate courageous and purposeful living, absent of regret.\r\n\r\nDo not let complacency cloud your potential to THINK BIG!\r\n\r\nDream big, have faith and be positive\r\nOvercome an inferiority complex\r\nPersevere through adversity and setbacks\r\nFace your fears and develop courage\r\nUse your time effectively', 'Ryuho Okawa', 'HS Press', '22', 13, 11, 'http://localhost/happykids/uploads/image/think_big.jpg', '2021-02-25 13:14:37', 2, '1'),
(60, 'Thinking Financially', 'In addition to being the founder and CEO of Happy Science Group, Master Ryuho Okawa is also a financial expert in both business and non-profit activities. In his late twenties, he worked as a financial elite, in Tokyo and New York, at one of the largest trading houses in Japan and was regarded as the one who is most likely to become company president. After leaving the company and establishing Happy Science at the age of 30, Master Okawa has been leading it for nearly 30 years, developing it into an international religious organization with more than 12 million members in over 100 countries.\r\n\r\nThinking Financially offers the essence of financial thinking that is needed in developmental stages of companies or non-profit organizations, from their launching to expanding and growing into big organizations. The book also gives details on how to invest our resources so that we may succeed in the future, which is one of the most difficult challenges in managing organizations. You&#039;ll see in this book the fundamentals of financial thinking that managers and financial experts should use to resolve their problems in everyday work.', 'Ryuho Okawa', 'HS Press', '22', 1, 6, 'http://localhost/happykids/uploads/image/thinking_financially.jpg', '2021-02-25 13:17:59', 2, '1');

-- --------------------------------------------------------

--
-- Table structure for table `category`
--

CREATE TABLE `category` (
  `id` int(11) NOT NULL,
  `category` varchar(100) NOT NULL,
  `description` text NOT NULL,
  `tag` varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `category`
--

INSERT INTO `category` (`id`, `category`, `description`, `tag`) VALUES
(1, 'History', 'Gain a truthful understanding of historical events', 'His'),
(2, 'Enlightenment', 'Buddhism and Modern-day Enlightenment', 'E'),
(3, 'Self Growth', 'Inspiration to develop a positive attitude, no matter what you face', 'SG'),
(4, 'Spiritual Messages', 'Interviews with guiding spirits of historical and contemporary figures', 'SM'),
(5, 'Current Events', 'Timely commentary on global affairs.', 'CEvents'),
(6, 'Higher Education', 'New perspectives to open new frontiers of academia', 'HEducation'),
(7, 'Others', 'Other types of books, except these category.', 'others'),
(8, 'Religion & Spirituality', 'Spiritual wisdom and answers to the questions about love, faith &amp; miracles', 'RS'),
(9, 'Politics & Social Sciences', 'Probe the thoughts of leaders to gain a true understanding of current events', 'PoliticS'),
(10, 'Predictions & Paranormal', 'Clairvoyant readings of the future; astonishing facts through remote viewing', 'Pp'),
(11, 'Success & Management', 'Insight into achieving continuous success in the face of difficulty', 'SuccessM'),
(12, 'The Law Series', 'Okawa\'s renowned anthology of spiritual teachings', 'Law'),
(13, 'Wellness', 'Open your mind to the healing power within', 'Well');

-- --------------------------------------------------------

--
-- Table structure for table `orders`
--

CREATE TABLE `orders` (
  `orderId` int(11) NOT NULL,
  `userId` int(11) NOT NULL,
  `ship_name` varchar(200) NOT NULL,
  `email` varchar(200) NOT NULL,
  `contact` varchar(50) NOT NULL,
  `address` text NOT NULL,
  `city` varchar(200) NOT NULL,
  `zipcode` varchar(200) NOT NULL,
  `total_price` varchar(200) NOT NULL,
  `paymentcheck` int(11) NOT NULL,
  `dateTime` timestamp NOT NULL DEFAULT current_timestamp(),
  `bookId` text NOT NULL,
  `quantity` text NOT NULL,
  `status` enum('1','0') NOT NULL DEFAULT '0' COMMENT '1 = accept | 0 = pending',
  `del_status` enum('1','0') NOT NULL DEFAULT '0' COMMENT '1 = Delivered | 0 = Not delivered'
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `orders`
--

INSERT INTO `orders` (`orderId`, `userId`, `ship_name`, `email`, `contact`, `address`, `city`, `zipcode`, `total_price`, `paymentcheck`, `dateTime`, `bookId`, `quantity`, `status`, `del_status`) VALUES
(1, 5, 'Perry', 'perry@hotmail.com', '0165263372', 'Penang', 'GeorgeTown', '10300', '112', 1, '2021-03-02 03:15:31', '51, 43, 59, 58', '1, 1, 1, 1', '1', '1'),
(2, 1, 'cherie', 'cheriequah@gmail.com', '0179841618', 'penang', 'GeorgeTown', '11900', '145', 1, '2021-03-02 03:17:57', '35, 11, 16, 57', '1, 1, 1, 1', '1', '0'),
(3, 1, 'cherie', 'cheriequah@gmail.com', '0179841618', 'penang', 'GeorgeTown', '11900', '31', 1, '2021-03-02 03:18:30', '56', '1', '1', '1'),
(4, 5, 'Perry', 'perry@hotmail.com', '0165263372', 'Penang', 'GeorgeTown', '10300', '197', 1, '2021-03-02 03:24:44', '46, 19, 13, 1', '1, 1, 1, 1', '0', '0'),
(5, 3, 'john', 'john@gmail.com', '0125346677', 'Penang', 'GeorgeTown', '10300', '211', 1, '2021-03-02 04:13:49', '59, 10, 7, 53, 55', '1, 1, 1, 1, 1', '0', '0'),
(7, 5, 'Perry', 'perry@hotmail.com', '0165263372', 'Penang', 'GeorgeTown', '10300', '31', 1, '2021-03-03 15:43:44', '50', '1', '0', '0'),
(8, 6, 'Ooi Isaac', 'isaacooi2001@gmail.com', '0174659977', '2C-3A-03, LINTANG SUNGAI ARA 14\r\nImperial Residence', 'Bayan Lepas', '11900', '41', 1, '2022-09-08 07:16:21', '57', '1', '0', '0'),
(9, 6, 'Ooi Isaac', 'isaacooi2001@gmail.com', '0174659977', '2C-3A-03, LINTANG SUNGAI ARA 14\r\nImperial Residence', 'Bayan Lepas', '11900', '32', 1, '2022-09-08 07:24:43', '59', '1', '1', '0'),
(10, 7, 'Ooi Isaac', 'isaacooi2001@gmail.com', '0174659977', '2C-3A-03, LINTANG SUNGAI ARA 14\r\nImperial Residence', 'Bayan Lepas', '11900', '43', 1, '2022-10-03 11:54:15', '58', '1', '1', '0'),
(12, 7, 'Ooi Isaac', 'isaacooi2001@gmail.com', '0174659977', '2C-3A-03, LINTANG SUNGAI ARA 14\r\nImperial Residence', 'Bayan Lepas', '11900', '70', 1, '2022-10-27 12:32:59', '60, 52', '2, 1', '0', '0'),
(13, 7, 'Ooi Isaac', 'ooiisaac@yahoo.com', '0174659977', '2C-3A-03, LINTANG SUNGAI ARA 14\r\nImperial Residence', 'Bayan Lepas', '11900', '32', 1, '2022-10-27 12:55:22', '60', '1', '1', '0');

-- --------------------------------------------------------

--
-- Table structure for table `reviews`
--

CREATE TABLE `reviews` (
  `id` int(11) NOT NULL,
  `review` text NOT NULL,
  `bookId` int(11) NOT NULL,
  `userId` int(11) NOT NULL,
  `dateTime` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `reviews`
--

INSERT INTO `reviews` (`id`, `review`, `bookId`, `userId`, `dateTime`) VALUES
(1, 'This book is awesome.', 41, 5, '2021-02-19 08:29:44'),
(2, 'Very interesting book. It\'s an eye opener for me.\r\n', 56, 1, '2021-03-02 10:03:33'),
(3, 'Really recommend this book for those who wants to find happiness.', 48, 5, '2021-03-03 13:13:57'),
(4, 'youuuuuuuuu', 57, 7, '2022-10-17 03:37:41'),
(5, 'qwe qweqeqw  qeqw eqwe qw ewq', 58, 7, '2022-10-27 12:54:08');

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE `users` (
  `id` int(11) NOT NULL,
  `name` varchar(200) NOT NULL,
  `contact` varchar(50) NOT NULL,
  `email` varchar(100) NOT NULL,
  `password` varchar(255) NOT NULL,
  `address` varchar(500) NOT NULL,
  `city` varchar(50) NOT NULL,
  `type` varchar(20) NOT NULL DEFAULT 'U',
  `createdate` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`id`, `name`, `contact`, `email`, `password`, `address`, `city`, `type`, `createdate`) VALUES
(1, 'user', '0179841618', 'user@gmail.com', '$2y$12$uZkma3thMSpKJztiZ2eGMuhtbiHw0r4hw4ns3xW7OxXHv1WASUEyC', 'Penang', 'GeorgeTown', 'U', '2021-01-15 13:35:11'),
(2, 'admin', '0179841618', 'admin@gmail.com', '$2y$12$bp5OVj7WiBUrG4sjVXdxXeGE.j5ag1Pt42k8XDnNmhy9p/2sCk4Dq', 'Penang', 'GeorgeTown', 'A', '2021-01-15 23:37:16'),
(3, 'user1', '0189345544', 'user1@gmail.com', '$2y$12$ivFEegkiv9sCnTAjl/r8w.zAztBslb2jxOs7WXD32m6g2T1V6ohiG', 'penang', 'GeorgeTown', 'U', '2021-01-25 13:44:01'),
(5, 'Perry', '0165263372', 'perry@hotmail.com', '$2y$12$OX.GPnTPUqfrw907sCSSOOzX6L8/9Eca3NGjgnc6zV9rafmYJ0oEe', 'Penang', 'GeorgeTown', 'U', '2021-02-19 06:48:25'),
(6, 'Isaac', '0174659977', 'isaacooi2001@gmail.com', '$2y$12$UFnUZb0S3htCbzvDzHk4cuNfA7bdERVHErhqJVMA48ajuLNjnCiZq', '2C-3A-03, LINTANG SUNGAI ARA 14', 'Bayan Lepas', 'U', '2022-09-08 07:15:56'),
(7, 'ttt', '8768787887', 'ooiisaac@yahoo.com', '$2y$12$/x2irCW/BYcukVaDezrVyOicEHQ2o3BWkEpEK1nGQKEul6qzanNSS', '2C-3A-03, LINTANG SUNGAI ARA 14', 'Bayan Lepas', 'U', '2022-10-03 06:39:18'),
(8, 'ttt', '0174659977', 'ttt@gmail.com', '$2y$12$s646sVQ6kM9KTwv3Z4rOoeyNZqeVVfA1O/T6WmzWglJ7FQcLlenyu', '2C-3A-03, LINTANG SUNGAI ARA 14', 'Bayan Lepas', 'U', '2022-10-27 12:50:22');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `books`
--
ALTER TABLE `books`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `category`
--
ALTER TABLE `category`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `orders`
--
ALTER TABLE `orders`
  ADD PRIMARY KEY (`orderId`);

--
-- Indexes for table `reviews`
--
ALTER TABLE `reviews`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `email` (`email`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `books`
--
ALTER TABLE `books`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=101;

--
-- AUTO_INCREMENT for table `category`
--
ALTER TABLE `category`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=14;

--
-- AUTO_INCREMENT for table `orders`
--
ALTER TABLE `orders`
  MODIFY `orderId` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=14;

--
-- AUTO_INCREMENT for table `reviews`
--
ALTER TABLE `reviews`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;

--
-- AUTO_INCREMENT for table `users`
--
ALTER TABLE `users`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=9;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
